from enum import Enum
from typing import Optional


class CrashType(Enum):
    """
    Categories of crashes detected by the fuzzer.
    """

    RUNTIME_ERROR = "RuntimeError"
    VALUE_ERROR = "ValueError"
    TYPE_ERROR = "TypeError"
    INDEX_ERROR = "IndexError"
    KEY_ERROR = "KeyError"
    ATTRIBUTE_ERROR = "AttributeError"
    ZERO_DIVISION = "ZeroDivisionError"
    MEMORY_ERROR = "MemoryError"
    ASSERTION_ERROR = "AssertionError"
    SYSTEM_EXIT = "SystemExit"
    UNKNOWN = "Unknown"


class CrashClassification:
    """
    Stores the classification of a single crash.
    """

    def __init__(
        self,
        crash_type: CrashType,
        message: str = ""
    ):
        self.crash_type = crash_type
        self.message = message

    @property
    def name(self) -> str:
        """
        Return the human-readable crash type.
        """

        return self.crash_type.value

    def __repr__(self) -> str:
        return (
            f"CrashClassification("
            f"type='{self.name}', "
            f"message={self.message!r}"
            f")"
        )


class CrashClassifier:
    """
    Classifies crashes using the error information
    produced by the target execution.

    The classifier primarily analyzes stderr and can
    also classify directly from exception information.
    """

    # =========================================================
    # EXCEPTION CLASSIFICATION
    # =========================================================

    def classify_exception(
        self,
        exception: BaseException
    ) -> CrashClassification:
        """
        Classify a Python exception directly.
        """

        exception_type = type(exception)

        mapping = {
            RuntimeError: CrashType.RUNTIME_ERROR,
            ValueError: CrashType.VALUE_ERROR,
            TypeError: CrashType.TYPE_ERROR,
            IndexError: CrashType.INDEX_ERROR,
            KeyError: CrashType.KEY_ERROR,
            AttributeError: CrashType.ATTRIBUTE_ERROR,
            ZeroDivisionError: CrashType.ZERO_DIVISION,
            MemoryError: CrashType.MEMORY_ERROR,
            AssertionError: CrashType.ASSERTION_ERROR,
            SystemExit: CrashType.SYSTEM_EXIT,
        }

        crash_type = mapping.get(
            exception_type,
            CrashType.UNKNOWN
        )

        return CrashClassification(
            crash_type=crash_type,
            message=str(exception)
        )

    # =========================================================
    # STDERR CLASSIFICATION
    # =========================================================

    def classify_stderr(
        self,
        stderr: bytes | str
    ) -> CrashClassification:
        """
        Classify a crash using stderr generated by
        a subprocess execution.
        """

        if isinstance(stderr, bytes):
            text = stderr.decode(
                "utf-8",
                errors="replace"
            )
        else:
            text = str(stderr)

        text = text.strip()

        if not text:
            return CrashClassification(
                CrashType.UNKNOWN
            )

        # -----------------------------------------------------
        # Match Python exception names
        # -----------------------------------------------------

        exception_map = {
            "RuntimeError": CrashType.RUNTIME_ERROR,
            "ValueError": CrashType.VALUE_ERROR,
            "TypeError": CrashType.TYPE_ERROR,
            "IndexError": CrashType.INDEX_ERROR,
            "KeyError": CrashType.KEY_ERROR,
            "AttributeError": CrashType.ATTRIBUTE_ERROR,
            "ZeroDivisionError": CrashType.ZERO_DIVISION,
            "MemoryError": CrashType.MEMORY_ERROR,
            "AssertionError": CrashType.ASSERTION_ERROR,
            "SystemExit": CrashType.SYSTEM_EXIT,
        }

        for exception_name, crash_type in exception_map.items():

            if exception_name in text:

                message = self._extract_message(
                    text,
                    exception_name
                )

                return CrashClassification(
                    crash_type=crash_type,
                    message=message
                )

        return CrashClassification(
            crash_type=CrashType.UNKNOWN,
            message=text
        )

    # =========================================================
    # EXECUTION RESULT CLASSIFICATION
    # =========================================================

    def classify(
        self,
        result
    ) -> CrashClassification:
        """
        Classify an ExecutionResult.

        The result is expected to contain stderr.
        """

        stderr = getattr(
            result,
            "stderr",
            b""
        )

        return self.classify_stderr(
            stderr
        )

    # =========================================================
    # MESSAGE EXTRACTION
    # =========================================================

    def _extract_message(
        self,
        text: str,
        exception_name: str
    ) -> str:
        """
        Extract the message following the exception name.

        Example:

            RuntimeError: Intentional fuzzing crash

        becomes:

            Intentional fuzzing crash
        """

        for line in reversed(
            text.splitlines()
        ):

            line = line.strip()

            if exception_name in line:

                parts = line.split(
                    exception_name,
                    1
                )

                if len(parts) == 2:

                    message = (
                        parts[1]
                        .lstrip(": ")
                        .strip()
                    )

                    if message:
                        return message

        return ""

    # =========================================================
    # CONVENIENCE HELPERS
    # =========================================================

    def is_known(
        self,
        classification: CrashClassification
    ) -> bool:
        """
        Return True if the crash was assigned a
        known exception category.
        """

        return (
            classification.crash_type
            != CrashType.UNKNOWN
        )

    def get_type(
        self,
        classification: CrashClassification
    ) -> str:
        """
        Return the human-readable crash type.
        """

        return classification.name

    def get_message(
        self,
        classification: CrashClassification
    ) -> str:
        """
        Return the extracted crash message.
        """

        return classification.message